language: node_js
branches:
  only:
    - master
node_js:
  - "0.11"
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install
after_success: grunt audit
after_script: grunt coveralls:tests
